//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/particleFieldSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdParticleFieldSchemaTokens,
    HD_PARTICLE_FIELD_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdTokenDataSourceHandle
HdParticleFieldSchema::GetKernelType() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdParticleFieldSchemaTokens->kernelType);
}

/*static*/
HdContainerDataSourceHandle
HdParticleFieldSchema::BuildRetained(
        const HdTokenDataSourceHandle &kernelType
)
{
    TfToken _names[1];
    HdDataSourceBaseHandle _values[1];

    size_t _count = 0;

    if (kernelType) {
        _names[_count] = HdParticleFieldSchemaTokens->kernelType;
        _values[_count++] = kernelType;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdParticleFieldSchema::Builder &
HdParticleFieldSchema::Builder::SetKernelType(
    const HdTokenDataSourceHandle &kernelType)
{
    _kernelType = kernelType;
    return *this;
}

HdContainerDataSourceHandle
HdParticleFieldSchema::Builder::Build()
{
    return HdParticleFieldSchema::BuildRetained(
        _kernelType
    );
}

/*static*/
HdParticleFieldSchema
HdParticleFieldSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdParticleFieldSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdParticleFieldSchemaTokens->particleField))
        : nullptr);
}

/*static*/
const TfToken &
HdParticleFieldSchema::GetSchemaToken()
{
    return HdParticleFieldSchemaTokens->particleField;
}

/*static*/
const HdDataSourceLocator &
HdParticleFieldSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE